/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.view.panes;

import javax.swing.SwingUtilities;
import sk.stu.fiit.controller.HracController;
import sk.stu.fiit.model.organisation.clients.Hrac;
import sk.stu.fiit.view.EntryFrame;

/**
 *
 * @author lucia
 */
public class ProfilHracaPane extends javax.swing.JPanel {

    private HracController controller;

    public ProfilHracaPane(HracController controller) {
        this.controller = controller;
        initComponents();
    }

    public ProfilHracaPane() {
        initComponents();
    }

    private void setHracInfo() {
        Hrac h = (Hrac) this.controller.getUserLoggedIn();
        labelMenoHraca.setText(h.getMeno());
        labelPrezyvka.setText(h.getLogin());

    }

    public void refresh() {
        this.setHracInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogUpravit = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfMenoDialog = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfPriezviskoDialog = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfMestoDialog = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfStatDialog = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        calDatumNarodenia = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        cbPohlavie = new javax.swing.JComboBox<>();
        btnVybratAvatar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        btnUlozitDialog = new javax.swing.JButton();
        labelMenoHraca = new javax.swing.JLabel();
        labelPrezyvka = new javax.swing.JLabel();
        MestoLabel = new javax.swing.JLabel();
        btnUpravitProfil = new javax.swing.JButton();
        Avatar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoriaZapasov = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        HistoriaTurnajov = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DatumRegistracieLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PocetZapasovLabel = new javax.swing.JLabel();
        VyhryLabel = new javax.swing.JLabel();
        PrehryLable = new javax.swing.JLabel();
        TurnajeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogOutHrac = new javax.swing.JButton();

        dialogUpravit.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Upraviù ˙daje");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Meno");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        tfMenoDialog.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(tfMenoDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Priezvisko");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        tfPriezviskoDialog.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(tfPriezviskoDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Mesto");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        tfMestoDialog.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(tfMestoDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("ät·t");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        tfStatDialog.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(tfStatDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("D·tum narodenia");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));
        jPanel2.add(calDatumNarodenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Pohlavie");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        cbPohlavie.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cbPohlavie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muû", "éena", "InÈ" }));
        jPanel2.add(cbPohlavie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 130, -1));

        btnVybratAvatar.setBackground(new java.awt.Color(102, 102, 102));
        btnVybratAvatar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVybratAvatar.setForeground(new java.awt.Color(255, 255, 255));
        btnVybratAvatar.setText("Vybraù avatar");
        jPanel2.add(btnVybratAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 130, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/default-avatar.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, 160));

        btnUlozitDialog.setBackground(new java.awt.Color(118, 155, 108));
        btnUlozitDialog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUlozitDialog.setForeground(new java.awt.Color(255, 255, 255));
        btnUlozitDialog.setText("Uloûiù");
        btnUlozitDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUlozitDialogMouseClicked(evt);
            }
        });
        jPanel2.add(btnUlozitDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 140, 30));

        dialogUpravit.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 550));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMenoHraca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMenoHraca.setForeground(new java.awt.Color(0, 0, 0));
        labelMenoHraca.setText("Cpavok");
        add(labelMenoHraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 220, 20));

        labelPrezyvka.setForeground(new java.awt.Color(102, 102, 102));
        labelPrezyvka.setText("Tu bude jeho prez˝vka");
        add(labelPrezyvka, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        MestoLabel.setForeground(new java.awt.Color(0, 0, 0));
        MestoLabel.setText("Mesto, öt·t?");
        add(MestoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        btnUpravitProfil.setBackground(new java.awt.Color(204, 204, 204));
        btnUpravitProfil.setForeground(new java.awt.Color(0, 0, 0));
        btnUpravitProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/edit.png"))); // NOI18N
        btnUpravitProfil.setText("Upraviù");
        btnUpravitProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpravitProfilMouseClicked(evt);
            }
        });
        add(btnUpravitProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/default-avatar.png"))); // NOI18N
        add(Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 170));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rating:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        RatingLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RatingLabel.setForeground(new java.awt.Color(0, 0, 0));
        RatingLabel.setText("2641");
        add(RatingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 70, -1));

        HistoriaZapasov.setBackground(new java.awt.Color(204, 204, 204));
        HistoriaZapasov.setForeground(new java.awt.Color(51, 51, 51));
        HistoriaZapasov.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cpavok vs Magnus Carlson 1:0 Mar 6, 2021", "Cpavok vs Hikaru Nakamura 1:0 Mar 5, 2021", "new DefaultListModel<Zapas>", "^^ do custom code v modeli", "a este v Code TypeParameters na Zapas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(HistoriaZapasov);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 360, 270));

        HistoriaTurnajov.setBackground(new java.awt.Color(204, 204, 204));
        HistoriaTurnajov.setForeground(new java.awt.Color(51, 51, 51));
        HistoriaTurnajov.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Meltwater 2021" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(HistoriaTurnajov);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 360, 270));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("D·tum registr·cie:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 880, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Z·pasy");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("TURNAJE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        DatumRegistracieLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DatumRegistracieLabel.setForeground(new java.awt.Color(0, 0, 0));
        DatumRegistracieLabel.setText("12-3-2021");
        add(DatumRegistracieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Turnaje:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Prehry:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("V˝hry:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("PoËet odohrat˝ch z·pasov:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        PocetZapasovLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PocetZapasovLabel.setForeground(new java.awt.Color(0, 153, 255));
        PocetZapasovLabel.setText("2");
        jPanel1.add(PocetZapasovLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        VyhryLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VyhryLabel.setForeground(new java.awt.Color(107, 179, 107));
        VyhryLabel.setText("2");
        jPanel1.add(VyhryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        PrehryLable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PrehryLable.setForeground(new java.awt.Color(238, 79, 79));
        PrehryLable.setText("0");
        jPanel1.add(PrehryLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        TurnajeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TurnajeLabel.setForeground(new java.awt.Color(0, 153, 255));
        TurnajeLabel.setText("1");
        jPanel1.add(TurnajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("äTATISTIKY");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RemÌzy:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("0");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 20, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 230, 170));

        btnLogOutHrac.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOutHrac.setForeground(new java.awt.Color(0, 0, 0));
        btnLogOutHrac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/logout.png"))); // NOI18N
        btnLogOutHrac.setText("Odhl·siù sa");
        btnLogOutHrac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogOutHracMouseReleased(evt);
            }
        });
        add(btnLogOutHrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutHracMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutHracMouseReleased
        this.controller.logOut();
        SwingUtilities.getWindowAncestor(this).dispose();
        EntryFrame.main();
    }//GEN-LAST:event_btnLogOutHracMouseReleased

    private void btnUpravitProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpravitProfilMouseClicked
        dialogUpravit.pack();
        dialogUpravit.setLocationRelativeTo(this);
        dialogUpravit.setVisible(true);
    }//GEN-LAST:event_btnUpravitProfilMouseClicked

    private void btnUlozitDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUlozitDialogMouseClicked
       
    }//GEN-LAST:event_btnUlozitDialogMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private javax.swing.JLabel DatumRegistracieLabel;
    private javax.swing.JList<String> HistoriaTurnajov;
    private javax.swing.JList<String> HistoriaZapasov;
    private javax.swing.JLabel MestoLabel;
    private javax.swing.JLabel PocetZapasovLabel;
    private javax.swing.JLabel PrehryLable;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JLabel TurnajeLabel;
    private javax.swing.JLabel VyhryLabel;
    private javax.swing.JButton btnLogOutHrac;
    private javax.swing.JButton btnUlozitDialog;
    private javax.swing.JButton btnUpravitProfil;
    private javax.swing.JButton btnVybratAvatar;
    private com.toedter.calendar.JDateChooser calDatumNarodenia;
    private javax.swing.JComboBox<String> cbPohlavie;
    private javax.swing.JDialog dialogUpravit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelMenoHraca;
    private javax.swing.JLabel labelPrezyvka;
    private javax.swing.JTextField tfMenoDialog;
    private javax.swing.JTextField tfMestoDialog;
    private javax.swing.JTextField tfPriezviskoDialog;
    private javax.swing.JTextField tfStatDialog;
    // End of variables declaration//GEN-END:variables
}
