/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.view.panes;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import sk.stu.fiit.controller.HracController;
import sk.stu.fiit.model.organisation.clients.Hrac;
import sk.stu.fiit.model.organisation.platform.turnaj.Turnaj;
import sk.stu.fiit.view.ViewUtils;
import sk.stu.fiit.view.dialogs.EditovatHracaDialog;
import sk.stu.fiit.view.dialogs.TurnajInfoDialog;

/**
 *
 * @author lucia
 * @author Martin Melisek
 */
public class ProfilHracaPane extends javax.swing.JPanel implements IViewRefresh {

    private HracController controller;

    private JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);

    public ProfilHracaPane(HracController controller) {
        this.controller = controller;
        initComponents();
    }

    public ProfilHracaPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOdohrateTurnaje = new javax.swing.JLabel();
        labelMeno = new javax.swing.JLabel();
        labelPrezyvka = new javax.swing.JLabel();
        MestoLabel = new javax.swing.JLabel();
        btnUpravitProfil = new javax.swing.JButton();
        iconAvatar = new javax.swing.JLabel();
        labelRating = new javax.swing.JLabel();
        labelRatingData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listZapasy = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTurnaje = new javax.swing.JList<>();
        labelDatumReg = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelZapasy = new javax.swing.JLabel();
        labelTurnaje = new javax.swing.JLabel();
        labelDatumRegData = new javax.swing.JLabel();
        paneStatistiky = new javax.swing.JPanel();
        labelTurnajeStat = new javax.swing.JLabel();
        labelPrehry = new javax.swing.JLabel();
        labelVyhry = new javax.swing.JLabel();
        labelPocetZap = new javax.swing.JLabel();
        labelPocetZapData = new javax.swing.JLabel();
        labelVyhryData = new javax.swing.JLabel();
        labelPrehryData = new javax.swing.JLabel();
        labelTurnajeData = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelRemizy = new javax.swing.JLabel();
        labelRemizyData = new javax.swing.JLabel();
        labelMesto = new javax.swing.JLabel();
        labelOrg = new javax.swing.JLabel();
        labelStat = new javax.swing.JLabel();
        labelPohlavie = new javax.swing.JLabel();
        labelOrgData = new javax.swing.JLabel();
        labelMestoData = new javax.swing.JLabel();
        labelStatData = new javax.swing.JLabel();
        labelDatumNarodeniaData = new javax.swing.JLabel();
        labelPohlavieData = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelOdohrateTurnaje.setBackground(new java.awt.Color(0, 0, 0));
        labelOdohrateTurnaje.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelOdohrateTurnaje.setForeground(new java.awt.Color(0, 0, 0));
        labelOdohrateTurnaje.setText("Nem·te ûiaden odohrat˝ turnaj...");
        add(labelOdohrateTurnaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        labelMeno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelMeno.setForeground(new java.awt.Color(0, 0, 0));
        labelMeno.setText("Cpavok");
        add(labelMeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 220, 20));

        labelPrezyvka.setForeground(new java.awt.Color(102, 102, 102));
        labelPrezyvka.setText("Prezyvka");
        add(labelPrezyvka, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        MestoLabel.setForeground(new java.awt.Color(0, 0, 0));
        MestoLabel.setText("D·tum narodenia:");
        add(MestoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        btnUpravitProfil.setBackground(new java.awt.Color(204, 204, 204));
        btnUpravitProfil.setForeground(new java.awt.Color(0, 0, 0));
        btnUpravitProfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/edit.png"))); // NOI18N
        btnUpravitProfil.setText("Upraviù");
        btnUpravitProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUpravitProfilMouseReleased(evt);
            }
        });
        add(btnUpravitProfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        iconAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/default-avatar.png"))); // NOI18N
        add(iconAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 170));

        labelRating.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelRating.setForeground(new java.awt.Color(0, 0, 0));
        labelRating.setText("Rating:");
        add(labelRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        labelRatingData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRatingData.setForeground(new java.awt.Color(0, 0, 0));
        labelRatingData.setText("2641");
        add(labelRatingData, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 70, -1));

        listZapasy.setBackground(new java.awt.Color(204, 204, 204));
        listZapasy.setForeground(new java.awt.Color(51, 51, 51));
        listZapasy.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cpavok vs Magnus Carlson 1:0 Mar 6, 2021", "Cpavok vs Hikaru Nakamura 1:0 Mar 5, 2021", "new DefaultListModel<Zapas>", "^^ do custom code v modeli", "a este v Code TypeParameters na Zapas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listZapasy);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 360, 270));

        listTurnaje.setBackground(new java.awt.Color(204, 204, 204));
        listTurnaje.setForeground(new java.awt.Color(51, 51, 51));
        listTurnaje.setModel(new DefaultListModel<Turnaj>());
        listTurnaje.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTurnaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listTurnajeMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(listTurnaje);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 360, 270));

        labelDatumReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDatumReg.setForeground(new java.awt.Color(0, 0, 0));
        labelDatumReg.setText("D·tum registr·cie:");
        add(labelDatumReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 880, 20));

        labelZapasy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelZapasy.setForeground(new java.awt.Color(204, 204, 204));
        labelZapasy.setText("Z·pasy");
        add(labelZapasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        labelTurnaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTurnaje.setForeground(new java.awt.Color(204, 204, 204));
        labelTurnaje.setText("TURNAJE");
        add(labelTurnaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        labelDatumRegData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDatumRegData.setForeground(new java.awt.Color(0, 0, 0));
        labelDatumRegData.setText("12-3-2021");
        add(labelDatumRegData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        paneStatistiky.setBackground(new java.awt.Color(204, 204, 204));
        paneStatistiky.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTurnajeStat.setForeground(new java.awt.Color(0, 0, 0));
        labelTurnajeStat.setText("Turnaje:");
        paneStatistiky.add(labelTurnajeStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        labelPrehry.setForeground(new java.awt.Color(0, 0, 0));
        labelPrehry.setText("Prehry:");
        paneStatistiky.add(labelPrehry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        labelVyhry.setForeground(new java.awt.Color(0, 0, 0));
        labelVyhry.setText("V˝hry:");
        paneStatistiky.add(labelVyhry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        labelPocetZap.setForeground(new java.awt.Color(0, 0, 0));
        labelPocetZap.setText("PoËet odohrat˝ch z·pasov:");
        paneStatistiky.add(labelPocetZap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        labelPocetZapData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPocetZapData.setForeground(new java.awt.Color(0, 153, 255));
        labelPocetZapData.setText("2");
        paneStatistiky.add(labelPocetZapData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        labelVyhryData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelVyhryData.setForeground(new java.awt.Color(107, 179, 107));
        labelVyhryData.setText("2");
        paneStatistiky.add(labelVyhryData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        labelPrehryData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPrehryData.setForeground(new java.awt.Color(238, 79, 79));
        labelPrehryData.setText("0");
        paneStatistiky.add(labelPrehryData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        labelTurnajeData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTurnajeData.setForeground(new java.awt.Color(0, 153, 255));
        labelTurnajeData.setText("1");
        paneStatistiky.add(labelTurnajeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("äTATISTIKY");
        paneStatistiky.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        labelRemizy.setBackground(new java.awt.Color(0, 0, 0));
        labelRemizy.setForeground(new java.awt.Color(0, 0, 0));
        labelRemizy.setText("RemÌzy:");
        paneStatistiky.add(labelRemizy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        labelRemizyData.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        labelRemizyData.setForeground(new java.awt.Color(102, 102, 102));
        labelRemizyData.setText("0");
        paneStatistiky.add(labelRemizyData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 20, -1));

        add(paneStatistiky, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 230, 170));

        labelMesto.setForeground(new java.awt.Color(0, 0, 0));
        labelMesto.setText("Mesto:");
        add(labelMesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        labelOrg.setForeground(new java.awt.Color(0, 0, 0));
        labelOrg.setText("Organizacia:");
        add(labelOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        labelStat.setForeground(new java.awt.Color(0, 0, 0));
        labelStat.setText("ät·t:");
        add(labelStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        labelPohlavie.setForeground(new java.awt.Color(0, 0, 0));
        labelPohlavie.setText("Pohlavie:");
        add(labelPohlavie, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        labelOrgData.setForeground(new java.awt.Color(0, 0, 0));
        labelOrgData.setText("Orga");
        add(labelOrgData, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        labelMestoData.setForeground(new java.awt.Color(0, 0, 0));
        labelMestoData.setText("DolnÈ »pavkovce");
        add(labelMestoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        labelStatData.setForeground(new java.awt.Color(0, 0, 0));
        labelStatData.setText("EurÛpa");
        add(labelStatData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        labelDatumNarodeniaData.setForeground(new java.awt.Color(0, 0, 0));
        labelDatumNarodeniaData.setText("01.04.2021");
        add(labelDatumNarodeniaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        labelPohlavieData.setForeground(new java.awt.Color(0, 0, 0));
        labelPohlavieData.setText("Dog");
        add(labelPohlavieData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpravitProfilMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpravitProfilMouseReleased
        EditovatHracaDialog dialog = new EditovatHracaDialog(this.parent, true, this.controller.getPrihlasenyHrac());
        dialog.showDialog();
        this.refresh();
    }//GEN-LAST:event_btnUpravitProfilMouseReleased

    private void listTurnajeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTurnajeMouseReleased
        Turnaj t = (Turnaj) listTurnaje.getSelectedValue();
        if (t == null) {
            return;
        }
        ViewUtils.showDialog(new TurnajInfoDialog(parent, true, t));
    }//GEN-LAST:event_listTurnajeMouseReleased
    private void setHracInfo() {
        Hrac h = this.controller.getPrihlasenyHrac();
        if (h.isFirstLogin()) {
            return;
        }
        labelMeno.setText(h.getMeno());
        labelPrezyvka.setText(h.getLogin());
        labelMestoData.setText(h.getMesto());
        labelStatData.setText(h.getStat());

        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        labelDatumRegData.setText(sdf.format(h.getDatumRegistracie()));
        labelDatumNarodeniaData.setText(sdf.format(h.getDatumNarodenia()));

        labelPohlavieData.setText(h.getPohlavie().toString());
        labelOrgData.setText(h.getOrg().getNazov());
        labelRatingData.setText(String.valueOf(h.getELO()));
        iconAvatar.setIcon(h.getAvatar().getImage());

        //TODO vypocty zapasov z turnajov, dal by som to do controllera lebo to bude treba aj do listov
    }

    public void naplnListTurnajov() {
        DefaultListModel<Turnaj> model = (DefaultListModel<Turnaj>) listTurnaje.getModel();
        model.setSize(0);
        ArrayList<Turnaj> turnaje = this.controller.getPrihlasenyHrac().getTurnaje();
        for (Turnaj t : turnaje) {
            if (t.isFinished()) {
                model.addElement(t);
            }
        }
        if (model.getSize() == 0) {
            labelOdohrateTurnaje.setVisible(true);
        } else {
            labelOdohrateTurnaje.setVisible(false);
        }
    }

    public void refresh() {
        this.setHracInfo();
        this.naplnListTurnajov();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MestoLabel;
    private javax.swing.JButton btnUpravitProfil;
    private javax.swing.JLabel iconAvatar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDatumNarodeniaData;
    private javax.swing.JLabel labelDatumReg;
    private javax.swing.JLabel labelDatumRegData;
    private javax.swing.JLabel labelMeno;
    private javax.swing.JLabel labelMesto;
    private javax.swing.JLabel labelMestoData;
    private javax.swing.JLabel labelOdohrateTurnaje;
    private javax.swing.JLabel labelOrg;
    private javax.swing.JLabel labelOrgData;
    private javax.swing.JLabel labelPocetZap;
    private javax.swing.JLabel labelPocetZapData;
    private javax.swing.JLabel labelPohlavie;
    private javax.swing.JLabel labelPohlavieData;
    private javax.swing.JLabel labelPrehry;
    private javax.swing.JLabel labelPrehryData;
    private javax.swing.JLabel labelPrezyvka;
    private javax.swing.JLabel labelRating;
    private javax.swing.JLabel labelRatingData;
    private javax.swing.JLabel labelRemizy;
    private javax.swing.JLabel labelRemizyData;
    private javax.swing.JLabel labelStat;
    private javax.swing.JLabel labelStatData;
    private javax.swing.JLabel labelTurnaje;
    private javax.swing.JLabel labelTurnajeData;
    private javax.swing.JLabel labelTurnajeStat;
    private javax.swing.JLabel labelVyhry;
    private javax.swing.JLabel labelVyhryData;
    private javax.swing.JLabel labelZapasy;
    private javax.swing.JList<Turnaj> listTurnaje;
    private javax.swing.JList<String> listZapasy;
    private javax.swing.JPanel paneStatistiky;
    // End of variables declaration//GEN-END:variables
}
