package sk.stu.fiit.view;

import java.util.Arrays;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import sk.stu.fiit.controller.EntryController;
import sk.stu.fiit.model.organisation.platform.Balik;
import sk.stu.fiit.utils.EntryConstants;
import sk.stu.fiit.utils.ViewUtils;

/**
 *
 * @author Martin Melisek
 */
public class EntryFrame extends javax.swing.JFrame {

    private final EntryController controller;
    private final javax.swing.JTextField[] registraciaHracaFields;
    private int registraciaType;

    public EntryFrame() {
        this.controller = new EntryController();
        initComponents();
        this.registraciaHracaFields = new javax.swing.JTextField[]{
            fieldRegistraciaMeno,
            fieldRegistraciaLogin,
            fieldRegistraciaHracaPassword,
            fieldRegistraciaHracaPasswordZnovu
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPripojit = new javax.swing.JDialog();
        panelPripojit = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        fieldLogin = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        btnPrihlasitOK = new javax.swing.JButton();
        btnRegistrovatHraca = new javax.swing.JButton();
        labelPrihlasitName = new javax.swing.JLabel();
        labelPrihlasitOrgName = new javax.swing.JLabel();
        dialogRegistrovatOrg = new javax.swing.JDialog();
        panelRegistrovatOrg = new javax.swing.JPanel();
        labelRegistraciaOrg = new javax.swing.JLabel();
        btnVytvoritSpravcu = new javax.swing.JButton();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelNazovRegOrg = new javax.swing.JLabel();
        fieldNazovRegOrg = new javax.swing.JTextField();
        labelAdresaRegOrg = new javax.swing.JLabel();
        fieldAdresaRegOrg = new javax.swing.JTextField();
        sliderBalik = new javax.swing.JSlider();
        labelBalik = new javax.swing.JLabel();
        labelBalikKapacita = new javax.swing.JLabel();
        labelBalikKapacitaData = new javax.swing.JLabel();
        labelBalikMaxPrihl = new javax.swing.JLabel();
        labelBalikMaxTurnajov = new javax.swing.JLabel();
        labelBalikMaxPrihlHracovData = new javax.swing.JLabel();
        labelBalikMaxTurnajovData = new javax.swing.JLabel();
        btnVytvoritOrg = new javax.swing.JButton();
        btnZobrazitDetaily = new javax.swing.JButton();
        dialogRegistrovatHraca = new javax.swing.JDialog();
        panelRegistraciaHraca = new javax.swing.JPanel();
        labelRegstraciaHraca = new javax.swing.JLabel();
        labelRegistraciaMeno = new javax.swing.JLabel();
        labelRegistraciaLogin = new javax.swing.JLabel();
        labelRegistraciaHeslo = new javax.swing.JLabel();
        labelRegistraciaHesloZnovu = new javax.swing.JLabel();
        fieldRegistraciaLogin = new javax.swing.JTextField();
        fieldRegistraciaMeno = new javax.swing.JTextField();
        btnRegistraciaHracaOK = new javax.swing.JButton();
        btnRegistraciaHracaZrusit = new javax.swing.JButton();
        fieldRegistraciaHracaPassword = new javax.swing.JPasswordField();
        fieldRegistraciaHracaPasswordZnovu = new javax.swing.JPasswordField();
        dialogDetailyRegistracie = new javax.swing.JDialog();
        panelDetailyRegistracie = new javax.swing.JPanel();
        scrollPaneDetaily = new javax.swing.JScrollPane();
        textAreaDetaily = new javax.swing.JTextArea();
        btnZavrietDetaily = new javax.swing.JButton();
        panelConnection = new javax.swing.JPanel();
        labelAdresa = new javax.swing.JLabel();
        fieldAdresa = new javax.swing.JTextField();
        btnRegistrovatOrg = new javax.swing.JButton();
        btnPripojit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        dialogPripojit.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogPripojit.setModal(true);
        dialogPripojit.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPripojit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLogin.setText("Login:");
        panelPripojit.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        fieldLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldLogin.setText("test");
        panelPripojit.add(fieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, -1));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPassword.setText("Heslo:");
        panelPripojit.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        fieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldPassword.setText("123");
        panelPripojit.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, -1));

        btnPrihlasitOK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrihlasitOK.setText("OK");
        btnPrihlasitOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrihlasitOKMouseClicked(evt);
            }
        });
        panelPripojit.add(btnPrihlasitOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btnRegistrovatHraca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrovatHraca.setText("Zaregistrovať sa");
        btnRegistrovatHraca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrovatHracaMouseClicked(evt);
            }
        });
        panelPripojit.add(btnRegistrovatHraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        labelPrihlasitName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPrihlasitName.setText("Prihlásenie do organizácie:");
        panelPripojit.add(labelPrihlasitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelPrihlasitOrgName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPrihlasitOrgName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrihlasitOrgName.setText("orgName");
        panelPripojit.add(labelPrihlasitOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        dialogPripojit.getContentPane().add(panelPripojit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 250));

        dialogRegistrovatOrg.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogRegistrovatOrg.setModal(true);
        dialogRegistrovatOrg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistrovatOrg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRegistraciaOrg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRegistraciaOrg.setText("Registrácia novej organizácie");
        panelRegistrovatOrg.add(labelRegistraciaOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnVytvoritSpravcu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVytvoritSpravcu.setText("Vytvoriť správcu");
        btnVytvoritSpravcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVytvoritSpravcuMouseClicked(evt);
            }
        });
        panelRegistrovatOrg.add(btnVytvoritSpravcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEmail.setText("E-mail:");
        panelRegistrovatOrg.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        fieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistrovatOrg.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 140, -1));

        labelNazovRegOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNazovRegOrg.setText("Názov organizácie: ");
        panelRegistrovatOrg.add(labelNazovRegOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        fieldNazovRegOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistrovatOrg.add(fieldNazovRegOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, -1));

        labelAdresaRegOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAdresaRegOrg.setText("Adresa organizácie:");
        panelRegistrovatOrg.add(labelAdresaRegOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        fieldAdresaRegOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistrovatOrg.add(fieldAdresaRegOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 140, -1));

        sliderBalik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sliderBalik.setMaximum(2);
        sliderBalik.setMinorTickSpacing(1);
        sliderBalik.setPaintTicks(true);
        sliderBalik.setSnapToTicks(true);
        sliderBalik.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderBalikStateChanged(evt);
            }
        });
        panelRegistrovatOrg.add(sliderBalik, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 190, 30));

        labelBalik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalik.setText("Balík");
        panelRegistrovatOrg.add(labelBalik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        labelBalikKapacita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalikKapacita.setText("Kapacita hráčov:");
        panelRegistrovatOrg.add(labelBalikKapacita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        labelBalikKapacitaData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalikKapacitaData.setText("jLabel1");
        panelRegistrovatOrg.add(labelBalikKapacitaData, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        labelBalikMaxPrihl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalikMaxPrihl.setText("Maximum hráčov na turnaji:");
        panelRegistrovatOrg.add(labelBalikMaxPrihl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        labelBalikMaxTurnajov.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalikMaxTurnajov.setText("Maximum turnajov:");
        panelRegistrovatOrg.add(labelBalikMaxTurnajov, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        labelBalikMaxPrihlHracovData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalikMaxPrihlHracovData.setText("jLabel1");
        panelRegistrovatOrg.add(labelBalikMaxPrihlHracovData, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        labelBalikMaxTurnajovData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelBalikMaxTurnajovData.setText("jLabel1");
        panelRegistrovatOrg.add(labelBalikMaxTurnajovData, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        btnVytvoritOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVytvoritOrg.setText("Registrovať");
        btnVytvoritOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVytvoritOrgMouseClicked(evt);
            }
        });
        panelRegistrovatOrg.add(btnVytvoritOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        btnZobrazitDetaily.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnZobrazitDetaily.setText("Detaily registrácie");
        btnZobrazitDetaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZobrazitDetailyMouseClicked(evt);
            }
        });
        panelRegistrovatOrg.add(btnZobrazitDetaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        dialogRegistrovatOrg.getContentPane().add(panelRegistrovatOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        dialogRegistrovatHraca.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogRegistrovatHraca.setModal(true);
        dialogRegistrovatHraca.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogRegistrovatHracaWindowClosed(evt);
            }
        });
        dialogRegistrovatHraca.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistraciaHraca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRegstraciaHraca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRegstraciaHraca.setText("Registrácia hráča");
        panelRegistraciaHraca.add(labelRegstraciaHraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        labelRegistraciaMeno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRegistraciaMeno.setText("Meno:");
        panelRegistraciaHraca.add(labelRegistraciaMeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        labelRegistraciaLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRegistraciaLogin.setText("Login:");
        panelRegistraciaHraca.add(labelRegistraciaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        labelRegistraciaHeslo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRegistraciaHeslo.setText("Heslo:");
        panelRegistraciaHraca.add(labelRegistraciaHeslo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        labelRegistraciaHesloZnovu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelRegistraciaHesloZnovu.setText("Heslo znovu:");
        panelRegistraciaHraca.add(labelRegistraciaHesloZnovu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        fieldRegistraciaLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistraciaHraca.add(fieldRegistraciaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 150, -1));

        fieldRegistraciaMeno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistraciaHraca.add(fieldRegistraciaMeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 150, -1));

        btnRegistraciaHracaOK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistraciaHracaOK.setText("OK");
        btnRegistraciaHracaOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistraciaHracaOKMouseClicked(evt);
            }
        });
        panelRegistraciaHraca.add(btnRegistraciaHracaOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        btnRegistraciaHracaZrusit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistraciaHracaZrusit.setText("Zrušiť");
        btnRegistraciaHracaZrusit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistraciaHracaZrusitMouseClicked(evt);
            }
        });
        panelRegistraciaHraca.add(btnRegistraciaHracaZrusit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        fieldRegistraciaHracaPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistraciaHraca.add(fieldRegistraciaHracaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, -1));

        fieldRegistraciaHracaPasswordZnovu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelRegistraciaHraca.add(fieldRegistraciaHracaPasswordZnovu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, -1));

        dialogRegistrovatHraca.getContentPane().add(panelRegistraciaHraca, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 300));

        dialogDetailyRegistracie.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialogDetailyRegistracie.setModal(true);
        dialogDetailyRegistracie.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDetailyRegistracie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textAreaDetaily.setEditable(false);
        textAreaDetaily.setColumns(20);
        textAreaDetaily.setLineWrap(true);
        textAreaDetaily.setRows(5);
        textAreaDetaily.setWrapStyleWord(true);
        scrollPaneDetaily.setViewportView(textAreaDetaily);

        panelDetailyRegistracie.add(scrollPaneDetaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 210));

        btnZavrietDetaily.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnZavrietDetaily.setText("Zavrieť");
        btnZavrietDetaily.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnZavrietDetailyMouseClicked(evt);
            }
        });
        panelDetailyRegistracie.add(btnZavrietDetaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        dialogDetailyRegistracie.getContentPane().add(panelDetailyRegistracie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eSachista");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConnection.setBackground(new java.awt.Color(255, 255, 255));
        panelConnection.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelConnection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAdresa.setBackground(new java.awt.Color(255, 255, 255));
        labelAdresa.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        labelAdresa.setForeground(new java.awt.Color(255, 255, 255));
        labelAdresa.setText("Adresa");
        panelConnection.add(labelAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        fieldAdresa.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        fieldAdresa.setText("sk.stu.fiit.vava");
        panelConnection.add(fieldAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 260, 40));

        btnRegistrovatOrg.setBackground(new java.awt.Color(118, 155, 108));
        btnRegistrovatOrg.setFont(new java.awt.Font("Candara", 0, 23)); // NOI18N
        btnRegistrovatOrg.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrovatOrg.setText("Zaregistrovať organizáciu");
        btnRegistrovatOrg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(118, 155, 108), 1, true));
        btnRegistrovatOrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrovatOrgMouseClicked(evt);
            }
        });
        panelConnection.add(btnRegistrovatOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 350, 50));

        btnPripojit.setBackground(new java.awt.Color(102, 102, 102));
        btnPripojit.setFont(new java.awt.Font("Candara", 0, 23)); // NOI18N
        btnPripojit.setForeground(new java.awt.Color(255, 255, 255));
        btnPripojit.setText("Pripojiť sa");
        btnPripojit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        btnPripojit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPripojitMouseClicked(evt);
            }
        });
        btnPripojit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPripojitActionPerformed(evt);
            }
        });
        panelConnection.add(btnPripojit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 350, 50));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelConnection.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 360, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelConnection.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 360, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/chess.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        panelConnection.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelConnection.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 350, 150));

        getContentPane().add(panelConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrihlasitOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrihlasitOKMouseClicked
        String login = fieldLogin.getText();
        char[] password = fieldPassword.getPassword();
        fieldPassword.setText("");
        if (!this.controller.pripojitHraca(login, password)) {
            JOptionPane.showMessageDialog(dialogPripojit, "Ucet neexistuje", "Invalid User", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        System.out.println("DEBUG: PRIHLASENIE FAJNOVUCKE"); // TODO CONTINUE.
        dialogPripojit.dispose();
        int loggedInId = this.controller.getPripojenyPouzivatel();
        switch (loggedInId) {
            case EntryConstants.LOGGED_IN_SPRAVCA:
                System.out.println("DEBUG: loggedInId = " + loggedInId);
                SpravcaFrame.main();
                break;
            case EntryConstants.LOGGED_IN_HRAC:
                System.out.println("DEBUG: loggedInId = " + loggedInId);
                HracFrame.main();
                break;
            default:
                System.err.println("DEBUG: NEOCAKAVANA CHYBA PRI PRIHLASOVANI");
                break;
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnPrihlasitOKMouseClicked

    private void btnRegistrovatHracaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrovatHracaMouseClicked
        this.registraciaType = EntryConstants.REGISTRUJ_HRACA;
        ViewUtils.clearFields(fieldLogin, fieldPassword);
        ViewUtils.showDialog(dialogRegistrovatHraca);
    }//GEN-LAST:event_btnRegistrovatHracaMouseClicked

    private void btnRegistraciaHracaOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistraciaHracaOKMouseClicked
        int status = this.vykonajRegistraciu(this.registraciaType); // skontroluj ci je mozne registrovat sa
        if (status == -1 || !this.skontrolujStatusRegistracieHrac(status)) {
            return;
        }
        dialogRegistrovatHraca.dispose();
    }//GEN-LAST:event_btnRegistraciaHracaOKMouseClicked

    private int vykonajRegistraciu(int registraciaType) {
        if (!ViewUtils.validateFieldsNotBlank(dialogRegistrovatHraca, registraciaHracaFields)) {
            return -1;
        }
        String meno = fieldRegistraciaMeno.getText();
        String login = fieldRegistraciaLogin.getText();
        char[] password = fieldRegistraciaHracaPassword.getPassword();
        char[] passwordZnovu = fieldRegistraciaHracaPasswordZnovu.getPassword();
        fieldRegistraciaHracaPassword.setText("");
        fieldRegistraciaHracaPasswordZnovu.setText("");
        // skontroluj pw
        if (!Arrays.equals(password, passwordZnovu)) {
            JOptionPane.showMessageDialog(dialogRegistrovatHraca, "Hesla sa nezhoduju.", "Invalid password", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
        return this.controller.registerPouzivatel(meno, login, password, registraciaType);

    }

    private boolean skontrolujStatusRegistracieHrac(int status) {
        if (status == EntryConstants.MENO_UZ_EXISTUJE) {
            JOptionPane.showMessageDialog(dialogRegistrovatHraca, "Tento pouzivatel uz existuje.", "Invalid Username", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (status == EntryConstants.KAPACITA_PREKROCENA) {
            JOptionPane.showMessageDialog(dialogRegistrovatHraca, "Kapacita bola prekrocena.", "Prekrocena kapacita", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void btnRegistraciaHracaZrusitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistraciaHracaZrusitMouseClicked
        ViewUtils.clearFields(this.registraciaHracaFields);
        dialogRegistrovatHraca.dispose();
    }//GEN-LAST:event_btnRegistraciaHracaZrusitMouseClicked

    private void dialogRegistrovatHracaWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogRegistrovatHracaWindowClosed
        ViewUtils.clearFields(this.registraciaHracaFields);
    }//GEN-LAST:event_dialogRegistrovatHracaWindowClosed

    private void btnVytvoritSpravcuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVytvoritSpravcuMouseClicked
        ViewUtils.showDialog(dialogRegistrovatHraca);

    }//GEN-LAST:event_btnVytvoritSpravcuMouseClicked

    private void sliderBalikStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBalikStateChanged
        DefaultBoundedRangeModel model = (DefaultBoundedRangeModel) sliderBalik.getModel();
        int index = model.getValue();
        this.updateBalikInfo(index);
    }//GEN-LAST:event_sliderBalikStateChanged

    private void btnZobrazitDetailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZobrazitDetailyMouseClicked
        String nazovOrg = fieldNazovRegOrg.getText();
        String adresaOrg = fieldAdresaRegOrg.getText();
        int balikId = ((DefaultBoundedRangeModel) sliderBalik.getModel()).getValue();
        String detailyRegistracie = this.controller.getDetailyRegistracieOrg(nazovOrg, adresaOrg, balikId);
        textAreaDetaily.setText(detailyRegistracie);
        ViewUtils.showDialog(dialogDetailyRegistracie);
    }//GEN-LAST:event_btnZobrazitDetailyMouseClicked

    private void btnVytvoritOrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVytvoritOrgMouseClicked
        int balikId = ((DefaultBoundedRangeModel) sliderBalik.getModel()).getValue();
        if (!ViewUtils.validateFieldsNotBlank(dialogRegistrovatOrg, fieldEmail, fieldNazovRegOrg, fieldAdresaRegOrg)) {
            return;
        }
        String nazovOrg = fieldNazovRegOrg.getText();
        String adresaOrg = fieldAdresaRegOrg.getText();
        int status = this.controller.registerOrg(nazovOrg, adresaOrg, balikId);
        if (!this.skontrolujStatusRegistracieOrg(status)) {
            return;
        }

        dialogRegistrovatOrg.dispose();
    }//GEN-LAST:event_btnVytvoritOrgMouseClicked

    private boolean skontrolujStatusRegistracieOrg(int status) {
        if (status == EntryConstants.MENO_UZ_EXISTUJE) {
            JOptionPane.showMessageDialog(dialogRegistrovatOrg, "Tato organizacia uz existuje", "Invalid input", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (status == EntryConstants.SPRAVCA_NEBOL_VYTVORENY) {
            JOptionPane.showMessageDialog(dialogRegistrovatOrg, "Spravca organizacie nebol vytvoreny", "Invalid input", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    public void updateBalikInfo(int index) {
        Balik b = this.controller.getBalik(index);
        labelBalikKapacitaData.setText(String.valueOf(b.getKapacitaPouzivatelov()));
        labelBalikMaxTurnajovData.setText(String.valueOf(b.getMaxPocetTurnajov()));
        labelBalikMaxPrihlHracovData.setText(String.valueOf(b.getMaxHracovTurnaja()));
    }


    private void btnZavrietDetailyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnZavrietDetailyMouseClicked
        dialogDetailyRegistracie.dispose();
    }//GEN-LAST:event_btnZavrietDetailyMouseClicked

    private void btnRegistrovatOrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrovatOrgMouseClicked
        this.controller.clearSpravca();
        this.registraciaType = EntryConstants.REGISTRUJ_SPRAVCU;
        this.updateBalikInfo(2);
        ViewUtils.showDialog(dialogRegistrovatOrg);
    }//GEN-LAST:event_btnRegistrovatOrgMouseClicked

    private void btnPripojitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPripojitMouseClicked
        String orgAdresa = fieldAdresa.getText();
        if (!this.controller.pripojitOrganizaciu(orgAdresa)) {
            JOptionPane.showMessageDialog(this, "Nepodarilo sa pripojit", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        labelPrihlasitOrgName.setText(this.controller.getOrgName());
        ViewUtils.showDialog(dialogPripojit);
    }//GEN-LAST:event_btnPripojitMouseClicked

    private void btnPripojitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPripojitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPripojitActionPerformed

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrihlasitOK;
    private javax.swing.JButton btnPripojit;
    private javax.swing.JButton btnRegistraciaHracaOK;
    private javax.swing.JButton btnRegistraciaHracaZrusit;
    private javax.swing.JButton btnRegistrovatHraca;
    private javax.swing.JButton btnRegistrovatOrg;
    private javax.swing.JButton btnVytvoritOrg;
    private javax.swing.JButton btnVytvoritSpravcu;
    private javax.swing.JButton btnZavrietDetaily;
    private javax.swing.JButton btnZobrazitDetaily;
    private javax.swing.JDialog dialogDetailyRegistracie;
    private javax.swing.JDialog dialogPripojit;
    private javax.swing.JDialog dialogRegistrovatHraca;
    private javax.swing.JDialog dialogRegistrovatOrg;
    private javax.swing.JTextField fieldAdresa;
    private javax.swing.JTextField fieldAdresaRegOrg;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JTextField fieldNazovRegOrg;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldRegistraciaHracaPassword;
    private javax.swing.JPasswordField fieldRegistraciaHracaPasswordZnovu;
    private javax.swing.JTextField fieldRegistraciaLogin;
    private javax.swing.JTextField fieldRegistraciaMeno;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelAdresa;
    private javax.swing.JLabel labelAdresaRegOrg;
    private javax.swing.JLabel labelBalik;
    private javax.swing.JLabel labelBalikKapacita;
    private javax.swing.JLabel labelBalikKapacitaData;
    private javax.swing.JLabel labelBalikMaxPrihl;
    private javax.swing.JLabel labelBalikMaxPrihlHracovData;
    private javax.swing.JLabel labelBalikMaxTurnajov;
    private javax.swing.JLabel labelBalikMaxTurnajovData;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNazovRegOrg;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPrihlasitName;
    private javax.swing.JLabel labelPrihlasitOrgName;
    private javax.swing.JLabel labelRegistraciaHeslo;
    private javax.swing.JLabel labelRegistraciaHesloZnovu;
    private javax.swing.JLabel labelRegistraciaLogin;
    private javax.swing.JLabel labelRegistraciaMeno;
    private javax.swing.JLabel labelRegistraciaOrg;
    private javax.swing.JLabel labelRegstraciaHraca;
    private javax.swing.JPanel panelConnection;
    private javax.swing.JPanel panelDetailyRegistracie;
    private javax.swing.JPanel panelPripojit;
    private javax.swing.JPanel panelRegistraciaHraca;
    private javax.swing.JPanel panelRegistrovatOrg;
    private javax.swing.JScrollPane scrollPaneDetaily;
    private javax.swing.JSlider sliderBalik;
    private javax.swing.JTextArea textAreaDetaily;
    // End of variables declaration//GEN-END:variables

}
