package sk.stu.fiit.view;

import java.awt.Color;
import java.awt.FontMetrics;
import javax.swing.SwingUtilities;
import sk.stu.fiit.controller.HracController;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import sk.stu.fiit.model.organisation.clients.Hrac;
import sk.stu.fiit.view.dialogs.EditovatHracaDialog;

/**
 *
 * @author Martin Melisek
 */
public class HracFrame extends javax.swing.JFrame {

    private HracController controller;

    public HracFrame() {
        this.controller = new HracController();
        initComponents();
        this.editInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        final String PRE_HTML = "<html><p style=\"text-align: left; width: 80px;\">";
        final String POST_HTML = "</p></html>";
        mainTabPane = new javax.swing.JTabbedPane();
        profilHracaPane1 = new sk.stu.fiit.view.panes.ProfilHracaPane(this.controller);
        zoznamTurnajovPanel1 = new sk.stu.fiit.view.panes.ZoznamTurnajovPane();
        aktivneTurnajePanel1 = new sk.stu.fiit.view.panes.AktivneTurnajePane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eSachista - Hráè");

        mainTabPane.setUI(new BasicTabbedPaneUI(){
            @Override
            protected int calculateTabWidth(
                int tabPlacement, int tabIndex, FontMetrics metrics) {
                return 150;
            }

            @Override
            protected int calculateTabHeight(int tabPlacement, int tabIndex, int fontHeight) {
                return 45;
            }
        });
        mainTabPane.setBackground(new java.awt.Color(0, 166, 172));
        mainTabPane.setForeground(new java.awt.Color(0, 0, 0));
        mainTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        mainTabPane.setFont(new java.awt.Font("Segoe UI", 0, 15));
        mainTabPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabPaneStateChanged(evt);
            }
        });
        mainTabPane.addTab("Profil", profilHracaPane1);
        mainTabPane.setIconAt(0, new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/user2.png")));
        mainTabPane.setTitleAt(0, PRE_HTML + "Profil" + POST_HTML);
        mainTabPane.addTab("Turnaje", zoznamTurnajovPanel1);
        mainTabPane.setIconAt(1, new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/trophy2.png")));
        mainTabPane.setTitleAt(1, PRE_HTML + "Turnaje" + POST_HTML);
        mainTabPane.addTab("Aktívne turnaje", aktivneTurnajePanel1);
        mainTabPane.setIconAt(2, new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/chess2.png")));
        mainTabPane.setTitleAt(2, PRE_HTML + "Aktívne turnaje" + POST_HTML);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainTabPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabPaneStateChanged
        // tu sa budu aktualizovat zaleÅ¾itosti z panelov ak je to treba.
        int selectedPane = mainTabPane.getSelectedIndex();
        switch (selectedPane) {
            case 0:
                profilHracaPane1.refresh();
                break;
            case 1:
                zoznamTurnajovPanel1.refresh();
                break;
            case 2:
                aktivneTurnajePanel1.refresh();
                break;
            case 3:
                
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_mainTabPaneStateChanged

    private void editInfo() {
        if (this.controller.getPrihlasenyHrac().isFirstLogin()) {
            EditovatHracaDialog dialog = new EditovatHracaDialog(this, true, this.controller.getPrihlasenyHrac());
            dialog.showDialog();
            profilHracaPane1.refresh();
        }
    }
    

    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HracFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HracFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HracFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HracFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Color c = new Color(0, 118, 121);
        javax.swing.UIManager.put("TabbedPane.selected", c);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HracFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sk.stu.fiit.view.panes.AktivneTurnajePane aktivneTurnajePanel1;
    private javax.swing.JTabbedPane mainTabPane;
    private sk.stu.fiit.view.panes.ProfilHracaPane profilHracaPane1;
    private sk.stu.fiit.view.panes.ZoznamTurnajovPane zoznamTurnajovPanel1;
    // End of variables declaration//GEN-END:variables
}
