package sk.stu.fiit.view;

import javax.swing.JOptionPane;
import sk.stu.fiit.controller.LoginController;
import sk.stu.fiit.utils.ViewUtils;

/**
 *
 * @author Martin Melisek
 */
public class LoginFrame extends javax.swing.JFrame {

    private LoginController controller;
    
    public LoginFrame() {
        this.controller = new LoginController(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialogPripojit = new javax.swing.JDialog();
        panelPripojit = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        fieldLogin = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        btnPrihlasitOK = new javax.swing.JButton();
        btnPrihlasitCancel = new javax.swing.JButton();
        labelPrihlasitName = new javax.swing.JLabel();
        labelPrihlasitOrgName = new javax.swing.JLabel();
        dialogRegistrovatOrg = new javax.swing.JDialog();
        panelConnection = new javax.swing.JPanel();
        labelVitajte = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelAdresa = new javax.swing.JLabel();
        fieldAdresa = new javax.swing.JTextField();
        labelPopis = new javax.swing.JLabel();
        btnPripojit = new javax.swing.JButton();
        btnRegistrovatOrg = new javax.swing.JButton();

        dialogPripojit.setModal(true);
        dialogPripojit.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPripojit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelLogin.setText("Login:");
        panelPripojit.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        fieldLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelPripojit.add(fieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 130, -1));

        labelPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPassword.setText("Heslo:");
        panelPripojit.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        fieldPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelPripojit.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        btnPrihlasitOK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrihlasitOK.setText("OK");
        panelPripojit.add(btnPrihlasitOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        btnPrihlasitCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrihlasitCancel.setText("Zrušiť");
        panelPripojit.add(btnPrihlasitCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        labelPrihlasitName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPrihlasitName.setText("Prihlásenie do organizácie:");
        panelPripojit.add(labelPrihlasitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        labelPrihlasitOrgName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPrihlasitOrgName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrihlasitOrgName.setText("orgName");
        panelPripojit.add(labelPrihlasitOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        dialogPripojit.getContentPane().add(panelPripojit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 240));

        dialogRegistrovatOrg.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eSachista");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelConnection.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelConnection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVitajte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelVitajte.setText("Vitajte v aplikácií");
        panelConnection.add(labelVitajte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 40));

        labelName.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        labelName.setForeground(new java.awt.Color(102, 69, 255));
        labelName.setText("eSachista");
        panelConnection.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 110, 40));

        labelAdresa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAdresa.setText("Adresa:");
        panelConnection.add(labelAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        fieldAdresa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fieldAdresa.setText("sk.stu.fiit.vava");
        panelConnection.add(fieldAdresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 240, 40));

        labelPopis.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelPopis.setText("najmodernejší plánovač šachových turnajov");
        panelConnection.add(labelPopis, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 280, 30));

        btnPripojit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPripojit.setText("Pripojiť sa");
        btnPripojit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPripojitMouseClicked(evt);
            }
        });
        panelConnection.add(btnPripojit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 40));

        btnRegistrovatOrg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrovatOrg.setText("Zaregistrovať organizáciu");
        panelConnection.add(btnRegistrovatOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 240, 40));

        getContentPane().add(panelConnection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPripojitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPripojitMouseClicked
        String orgAdresa = fieldAdresa.getText();
        if(!this.controller.pripojitOrganizaciu(orgAdresa)){
            JOptionPane.showMessageDialog(this, "Nepodarilo sa pripojit", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }
        labelPrihlasitOrgName.setText(this.controller.getOrgName());
        ViewUtils.showDialog(dialogPripojit);
    }//GEN-LAST:event_btnPripojitMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrihlasitCancel;
    private javax.swing.JButton btnPrihlasitOK;
    private javax.swing.JButton btnPripojit;
    private javax.swing.JButton btnRegistrovatOrg;
    private javax.swing.JDialog dialogPripojit;
    private javax.swing.JDialog dialogRegistrovatOrg;
    private javax.swing.JTextField fieldAdresa;
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JLabel labelAdresa;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPopis;
    private javax.swing.JLabel labelPrihlasitName;
    private javax.swing.JLabel labelPrihlasitOrgName;
    private javax.swing.JLabel labelVitajte;
    private javax.swing.JPanel panelConnection;
    private javax.swing.JPanel panelPripojit;
    // End of variables declaration//GEN-END:variables
}
