/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.stu.fiit.view;

/**
 *
 * @author lucia
 */
public class ProfilHracaPane extends javax.swing.JPanel {

    /**
     * Creates new form jpProfilHraca
     */
    public ProfilHracaPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenoLabel = new javax.swing.JLabel();
        PrezyvkaLabel = new javax.swing.JLabel();
        MestoLabel = new javax.swing.JLabel();
        UpravitButton = new javax.swing.JButton();
        Avatar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoriaZapasov = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        HistoriaTurnajov = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DatumRegistracieLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PocetZapasovLabel = new javax.swing.JLabel();
        VyhryLabel = new javax.swing.JLabel();
        PrehryLable = new javax.swing.JLabel();
        TurnajeLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        MenoLabel.setForeground(new java.awt.Color(0, 0, 0));
        MenoLabel.setText("Cpavok");
        add(MenoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 220, 20));

        PrezyvkaLabel.setForeground(new java.awt.Color(102, 102, 102));
        PrezyvkaLabel.setText("Tu bude jeho prezývka");
        add(PrezyvkaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        MestoLabel.setForeground(new java.awt.Color(0, 0, 0));
        MestoLabel.setText("Mesto, štát?");
        add(MestoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        UpravitButton.setBackground(new java.awt.Color(153, 153, 153));
        UpravitButton.setForeground(new java.awt.Color(0, 0, 0));
        UpravitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/edit.png"))); // NOI18N
        UpravitButton.setText("Upraviť");
        add(UpravitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/default-avatar.png"))); // NOI18N
        add(Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Rating:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        RatingLabel.setForeground(new java.awt.Color(0, 0, 0));
        RatingLabel.setText("2641");
        add(RatingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 50, -1));

        HistoriaZapasov.setBackground(new java.awt.Color(204, 204, 204));
        HistoriaZapasov.setForeground(new java.awt.Color(102, 102, 102));
        HistoriaZapasov.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cpavok vs Magnus Carlson 1:0 Mar 6, 2021", "Cpavok vs Hikaru Nakamura 1:0 Mar 5, 2021" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(HistoriaZapasov);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 360, 270));

        HistoriaTurnajov.setBackground(new java.awt.Color(204, 204, 204));
        HistoriaTurnajov.setForeground(new java.awt.Color(102, 102, 102));
        HistoriaTurnajov.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Meltwater 2021" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(HistoriaTurnajov);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 360, 270));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dátum registrácie:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ŠTATISTIKA");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 860, 20));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Zápasy");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Turnaje");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        DatumRegistracieLabel.setForeground(new java.awt.Color(0, 0, 0));
        DatumRegistracieLabel.setText("jLabel14");
        add(DatumRegistracieLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Turnaje:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Prehry:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Výhry:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Počet odohratých zápasov:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        PocetZapasovLabel.setForeground(new java.awt.Color(255, 255, 255));
        PocetZapasovLabel.setText("jLabel15");
        jPanel1.add(PocetZapasovLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        VyhryLabel.setForeground(new java.awt.Color(255, 255, 255));
        VyhryLabel.setText("jLabel16");
        jPanel1.add(VyhryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        PrehryLable.setForeground(new java.awt.Color(255, 255, 255));
        PrehryLable.setText("jLabel17");
        jPanel1.add(PrehryLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        TurnajeLabel.setForeground(new java.awt.Color(255, 255, 255));
        TurnajeLabel.setText("jLabel18");
        jPanel1.add(TurnajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 260, 160));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sk/stu/fiit/obrazky/logout.png"))); // NOI18N
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private javax.swing.JLabel DatumRegistracieLabel;
    private javax.swing.JList<String> HistoriaTurnajov;
    private javax.swing.JList<String> HistoriaZapasov;
    private javax.swing.JLabel MenoLabel;
    private javax.swing.JLabel MestoLabel;
    private javax.swing.JLabel PocetZapasovLabel;
    private javax.swing.JLabel PrehryLable;
    private javax.swing.JLabel PrezyvkaLabel;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JLabel TurnajeLabel;
    private javax.swing.JButton UpravitButton;
    private javax.swing.JLabel VyhryLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
