package sk.stu.fiit.view;

import java.awt.Color;
import sk.stu.fiit.controller.SpravcaController;
import sk.stu.fiit.model.organisation.clients.Pouzivatel;

/**
 *
 * @author Martin Melisek
 */
public class SpravcaFrame extends javax.swing.JFrame {

    private SpravcaController controller;

    public SpravcaFrame() {
        this.controller = new SpravcaController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        spravcaPrehladPane2 = new sk.stu.fiit.view.SpravcaPrehladPane();
        turnajePane1 = new sk.stu.fiit.view.TurnajePane();
        clenoviaPane1 = new sk.stu.fiit.view.ClenoviaPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(935, 655));
        setPreferredSize(new java.awt.Dimension(935, 655));

        jTabbedPane1.setBackground(new java.awt.Color(0, 166, 172));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTabbedPane1.addTab("Prehľad", spravcaPrehladPane2);
        jTabbedPane1.addTab("Turnaje", turnajePane1);
        jTabbedPane1.addTab("Členovia", clenoviaPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpravcaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpravcaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpravcaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpravcaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        Color c = new Color(0,118,121);
        javax.swing.UIManager.put("TabbedPane.selected", c);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpravcaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sk.stu.fiit.view.ClenoviaPane clenoviaPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private sk.stu.fiit.view.SpravcaPrehladPane spravcaPrehladPane2;
    private sk.stu.fiit.view.TurnajePane turnajePane1;
    // End of variables declaration//GEN-END:variables
}
