package sk.stu.fiit.view.dialogs;

import java.util.Date;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import sk.stu.fiit.controller.TurnajController;
import sk.stu.fiit.exceptions.MaxPocetTurnajovException;
import sk.stu.fiit.model.organisation.platform.Turnaj;
import sk.stu.fiit.model.organisation.platform.TurnajFormat;
import sk.stu.fiit.utils.ViewUtils;

/**
 *
 * @author Martin Melisek
 */
public class VytvoritTurnajDialog extends javax.swing.JDialog {

    private static final Logger logger = LoggerFactory.getLogger(VytvoritTurnajDialog.class);

    private TurnajController controller;

    public VytvoritTurnajDialog(java.awt.Frame parent, boolean modal, TurnajController controller) {
        super(parent, modal);
        this.controller = controller;
        this.controller.setNovyTurnaj(null);
        initComponents();
        datePicker.setMinSelectableDate(new Date());
    }

    public VytvoritTurnajDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        btnVytvorit = new javax.swing.JButton();
        labelCasovyLimit = new javax.swing.JLabel();
        spinnerMin = new javax.swing.JSpinner();
        labelMin = new javax.swing.JLabel();
        fieldMiestoKonania = new javax.swing.JTextField();
        labelVytvoritTurnaj = new javax.swing.JLabel();
        labelFormat = new javax.swing.JLabel();
        datePicker = new com.toedter.calendar.JDateChooser();
        spinnerLimitMin = new javax.swing.JSpinner();
        fieldNazov = new javax.swing.JTextField();
        spinnerHrs = new javax.swing.JSpinner();
        labelSec = new javax.swing.JLabel();
        labelInc = new javax.swing.JLabel();
        labelDatum = new javax.swing.JLabel();
        labelCas = new javax.swing.JLabel();
        comboboxFormat = new javax.swing.JComboBox<>();
        spinnerLimitSec = new javax.swing.JSpinner();
        labelMiestoKonania = new javax.swing.JLabel();
        labelNazov = new javax.swing.JLabel();
        spinnerLimitInc = new javax.swing.JSpinner();
        labelOddelovac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVytvorit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVytvorit.setText("Vytvoriù");
        btnVytvorit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVytvoritMouseReleased(evt);
            }
        });
        mainPane.add(btnVytvorit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        labelCasovyLimit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCasovyLimit.setText("»asov˝ limit:");
        mainPane.add(labelCasovyLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        spinnerMin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerMin.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        mainPane.add(spinnerMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 80, -1));

        labelMin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelMin.setText("min");
        mainPane.add(labelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        fieldMiestoKonania.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainPane.add(fieldMiestoKonania, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        labelVytvoritTurnaj.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelVytvoritTurnaj.setText("Vytvoriù turnaj");
        mainPane.add(labelVytvoritTurnaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        labelFormat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelFormat.setText("Form·t:");
        mainPane.add(labelFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        datePicker.setDateFormatString("dd.MM.yyyy");
        datePicker.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainPane.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 162, 180, 30));

        spinnerLimitMin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerLimitMin.setModel(new javax.swing.SpinnerNumberModel(10, 1, null, 1));
        mainPane.add(spinnerLimitMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 80, -1));

        fieldNazov.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mainPane.add(fieldNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        spinnerHrs.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerHrs.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        mainPane.add(spinnerHrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, -1));

        labelSec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSec.setText("sec");
        mainPane.add(labelSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        labelInc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelInc.setText("inkrement");
        mainPane.add(labelInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        labelDatum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDatum.setText("D·tum konania:");
        mainPane.add(labelDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        labelCas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCas.setText("»as zaËiatku:");
        mainPane.add(labelCas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        comboboxFormat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboboxFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Round Robin", "Swiss", "Single Elimination" }));
        mainPane.add(comboboxFormat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 180, -1));

        spinnerLimitSec.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerLimitSec.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        mainPane.add(spinnerLimitSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 80, -1));

        labelMiestoKonania.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelMiestoKonania.setText("Miesto konania:");
        mainPane.add(labelMiestoKonania, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        labelNazov.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNazov.setText("N·zov turnaja:");
        mainPane.add(labelNazov, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        spinnerLimitInc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spinnerLimitInc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        mainPane.add(spinnerLimitInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 80, -1));

        labelOddelovac.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelOddelovac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOddelovac.setText(":");
        mainPane.add(labelOddelovac, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 20, 30));

        getContentPane().add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVytvoritMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVytvoritMouseReleased
        if (!ViewUtils.validateFieldsNotBlank(this, fieldNazov, fieldMiestoKonania)) {
            logger.warn("Neboli vyplnene vsetky fieldy");
            return;
        }
        String nazov = fieldNazov.getText();
        String miesto = fieldMiestoKonania.getText();
        try {
            spinnerHrs.commitEdit();
            spinnerMin.commitEdit();
        } catch (java.text.ParseException e) {
            logger.warn("Hodnota v poli cas zacatia bola mimo rozsahu");
        }
        int zaciatokHrs = (Integer) spinnerHrs.getValue();
        int zaciatokMin = (Integer) spinnerMin.getValue();
        
        int formatIndex = comboboxFormat.getSelectedIndex();
        TurnajFormat format = TurnajFormat.values()[formatIndex];
        int limitMin = (Integer) spinnerLimitMin.getValue();
        int limitSec = (Integer) spinnerLimitSec.getValue();
        int increment = (Integer) spinnerLimitInc.getValue();
        try {
            logger.info("Ukladam turnaj");
            this.controller.saveTurnaj(format, nazov, miesto, datePicker.getDate(), zaciatokHrs, zaciatokMin, limitMin, limitSec, increment);
            logger.info("Turnaj " + nazov + " ulozeny");
        } catch (NullPointerException ex) {
            logger.error("NEPLATNY DATUM");
            JOptionPane.showMessageDialog(this, "Neplatny datum");
            return;
        } catch (MaxPocetTurnajovException e){
            JOptionPane.showMessageDialog(this, "Bol prekroceny maximalny pocet turnajov");
            return;
        }
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_btnVytvoritMouseReleased

    public Turnaj showDialog() {
        ViewUtils.showDialog(this);
        return this.controller.getNovyTurnaj();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VytvoritTurnajDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VytvoritTurnajDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VytvoritTurnajDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VytvoritTurnajDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VytvoritTurnajDialog dialog = new VytvoritTurnajDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVytvorit;
    private javax.swing.JComboBox<String> comboboxFormat;
    private com.toedter.calendar.JDateChooser datePicker;
    private javax.swing.JTextField fieldMiestoKonania;
    private javax.swing.JTextField fieldNazov;
    private javax.swing.JLabel labelCas;
    private javax.swing.JLabel labelCasovyLimit;
    private javax.swing.JLabel labelDatum;
    private javax.swing.JLabel labelFormat;
    private javax.swing.JLabel labelInc;
    private javax.swing.JLabel labelMiestoKonania;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel labelNazov;
    private javax.swing.JLabel labelOddelovac;
    private javax.swing.JLabel labelSec;
    private javax.swing.JLabel labelVytvoritTurnaj;
    private javax.swing.JPanel mainPane;
    private javax.swing.JSpinner spinnerHrs;
    private javax.swing.JSpinner spinnerLimitInc;
    private javax.swing.JSpinner spinnerLimitMin;
    private javax.swing.JSpinner spinnerLimitSec;
    private javax.swing.JSpinner spinnerMin;
    // End of variables declaration//GEN-END:variables
}
